### PR TITLE
Cleanup Start scripts, Fix kernel download

### LINKED ISSUE #42: Publish Release and verify kernel url
https://github.com/dhschall/gem5-svr-bench/blob/cd669856d3dda955bcfe8097d93c52bdee457b57/image/Makefile#L65

### PR DESCRIPTION
**Pull request by shadowcpy**
This PR removes the flaky support for `m5 exit` (which was only included for diagnostic purposes), which fixes nodeapp and mediawiki.

Additionally, the kernel release download url in `image/Makefile` is now correct.

Closes #42

### CODE REVIEW

File: image/files/gem5_init.sh [hunk 1]
```diff
@@ -1,25 +1,13 @@
 #!/bin/bash
 
-if [ $(uname -i) == "aarch64" ];
```
Comment (dhschall) [inline image/files/gem5_init.sh:3]: Have you tried this on both x86 and Arm?

File: scripts/run_all.sh [hunk 2]
```diff
@@ -26,9 +26,9 @@
 set -xu
 
 GEM5=./../build/ALL/gem5.opt
-GEM5_CONFIG=./gem5-configs/fs-fdp.py
+GEM5_CONFIG=./gem5-configs/fs-multiarch.py
 
-ARCH="amd64"
+ARCH="arm64"
```
Comment (dhschall) [inline scripts/run_all.sh:31]:
```suggestion
ARCH="amd64"
```
I suggest using as default x86 as most people might not have an Arm machine

File: gem5-configs/arm-simple.py
Comment (dhschall) [inline gem5-configs/arm-simple.py:1]: I would prefer to have one `simple` script and one `fdp` script.

**Review by dhschall — CHANGES_REQUESTED** [review]
Thanks for making the changes and the suggestions.

However, one thing we should do is to have one `multiarch` script that uses the default config without the dedicated configurations for the core, bpu and the caches needed for fdp. This is used to create the checkpoints and do simple experiments.

The second is the FDP multiarch script. It contains all customization needed for FDP.
However, it does not include anything related to creating the checkpoints.

File: image/files/gem5_init.sh (hunk 1 above)
Comment (shadowcpy) [reply image/files/gem5_init.sh:3]: This works on both platforms

**Review by dhschall — APPROVED** [review]
Nice! Looks good to me. Thank you
